### ISSUE TITLE
There are 0 courses available

### ISSUE THREAD

**Issue by nitay93** [jansenicus/www-coursera-downloader#16]
The program shows that I don't have any courses on coursera even though I have many.

**Comment by peporiz0r** [comment]
same here

**Comment by webservicesTSE** [comment]
Is this still an open issue? I've encountered it as well.

**Comment by monis01** [comment]
same here,
This is what I get :  "There are 0 courses available".
why is it?

**Comment by emilyasterjones** [comment]
The problem is in line 207 
`selector = 'div.headline-1-text.c-dashboard-course-course-name'`
I think Coursera change their CSS. From what I can tell, the selector needs to match:
`<h4 class="headline-1-text" data-courselenium="course-name" data-reactid="120">Course Name</h4>`
`courses = browser.find_by_css(selector)` in line 209 doesn't work because the selector doesn't match anything, so len(courses) is 0.

**Comment by emilyasterjones** [comment]
This repo has been neglected and so isn't updated to accommodate the new "on-demand" platform Coursera rolled out July 1, 2016. Use this downloader instead: https://github.com/coursera-dl/coursera-dl. It's much faster, downloads everything (not just videos), and actually works.
